### ISSUE TITLE
Resolver Folder Structure

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-graphql-api#46]
Resolvers should be abstracted to their individual file. Each resolver shall have it's own __.js__ file, along with an associated __.test.js__ file. 

The Folder Stucture of the Resolvers folder should match the hiarchy of the resolvers object. For Example:

```javascript
const resolvers = {
  Query: {
      allPeople,
      somePeolple
  },
  Mutation: {
      changePerson
  },
  Person {
      email
  }
}
```

would match files

* resolvers
  * Query
    * allPeople.js
    * somePeople.js
  * Mutation
    * changePerson
  * Person
    * email

### Tasks

* [ ] New Folder Structure
* [ ] Import resolvers from files
* [ ] unit tests work
